version: '3'
services:
  rosbase:
    image: "sausy/devshell:${ARCHITECTUR}"
    build:
      context: .
      args:
        ROS_DIST: ${ROSVERSION}
        PLATFORM: ${ARCHITECTUR}
      dockerfile: Dockerfile
  devshell:
    image: "sausy/devshell:${ARCHITECTUR}"
    container_name: devshell
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    user: "userdev"
    working_dir: "/home/userdev"
    volumes:
      - "~/Projects/:/home/userdev/Projects"
      - "./entry/entry.sh:/entry/entry.sh"
