version: '3'
services:
  commonbash_build:
    image: "${DOCKHUB_USER}/commonbash:${ARCHITECTUR}_${OS_VERSION}"
    build:
      context: .
      args:
        OS_VERSION: ${OS_VERSION}
        PLATFORM: ${ARCHITECTUR}
      dockerfile: Dockerfile
  commonbash:
    image: "${DOCKHUB_USER}/commonbash:${ARCHITECTUR}_${OS_VERSION}"
    container_name: commonbash
    hostname: commonbash
    network_mode: "host"
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - /dev:/dev
