ARG PLATFORM
ARG OS_VERSION
FROM --platform=linux/$PLATFORM ubuntu:$OS_VERSION

ARG ROS_DIST

RUN mkdir /src && \
    echo "" > /src/entry.sh && \
    chmod +x /src/entry.sh

COPY ./entry.sh /src/entry.sh

RUN mkdir /data && \
    apt-get update && \
    apt-get install -y sudo && \
    DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq tzdata && \
    DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration && \
    apt-get install -y git nano curl man wget unzip tar gnupg2 && \
    apt-get install -y vim lsb-release lsb-core build-essential autoconf libtool cmake pkg-config && \
    #====== add user userdev:ubuntu ==== && \
    echo "root:ubuntu" | chpasswd && \
    useradd -ms /bin/bash userdev && \
    echo "userdev:ubuntu" | chpasswd && \
    adduser userdev sudo && \
    echo "userdev ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    #====== install python stuff ==== && \
    apt-get install -y python3-dev python3 python3-pip && \
    #apt-get install -y python-dev python-pip \
    apt-get install -y libssl-dev libffi-dev && \
    pip3 install --user --upgrade pip && \
    #====== PRE INSTALL ROS 1 ==== && \
    sudo locale-gen en_US en_US.UTF-8 && \
    sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 && \
    #====== PRE INSTALL ROS 2 ==== && \
    sudo locale-gen en_US en_US.UTF-8 && \
    sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    sudo apt-get update && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add - && \
    sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'

USER userdev
WORKDIR /home/userdev

CMD bash -C '/src/entry.sh';'bash'
